// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJFj5fp3UNel8KllKE0t49o1i60PP6Og',
    appId: '1:926999923553:web:24df79761783bf53b39320',
    messagingSenderId: '926999923553',
    projectId: 'messagerie-3809f',
    authDomain: 'messagerie-3809f.firebaseapp.com',
    storageBucket: 'messagerie-3809f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFUweNxXcRUneQT-_YluPeHQ6xbsHmT0Q',
    appId: '1:926999923553:android:0ec6043de27b5d8fb39320',
    messagingSenderId: '926999923553',
    projectId: 'messagerie-3809f',
    storageBucket: 'messagerie-3809f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvxujAMDEa0LC30woRy8B4yU1VCU-uoKs',
    appId: '1:926999923553:ios:f2a0c20c432a1e71b39320',
    messagingSenderId: '926999923553',
    projectId: 'messagerie-3809f',
    storageBucket: 'messagerie-3809f.appspot.com',
    iosBundleId: 'com.example.projetfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvxujAMDEa0LC30woRy8B4yU1VCU-uoKs',
    appId: '1:926999923553:ios:91572a2c0960a512b39320',
    messagingSenderId: '926999923553',
    projectId: 'messagerie-3809f',
    storageBucket: 'messagerie-3809f.appspot.com',
    iosBundleId: 'com.example.projetfinal.RunnerTests',
  );
}
